"""
JARVIS Ollama LLM Client Module.

Implements the BaseLLMClient interface to communicate asynchronously with a local
Ollama language model instance using httpx.
"""

import json
import logging
from typing import AsyncIterator, Dict, Any, Optional
import httpx

from llm.base import BaseLLMClient

logger = logging.getLogger(__name__)


class OllamaClient(BaseLLMClient):
    """
    Asynchronous client wrapper for local Ollama language models.
    """

    def __init__(self, model_name: str = "llama3:8b", api_base: str = "http://localhost:11434", timeout: float = 30.0) -> None:
        """
        Initializes the Ollama Client.

        Args:
            model_name: The targeting model identifier (e.g. 'llama3:8b').
            api_base: The local base URL of the Ollama server.
            timeout: Maximum timeout in seconds for API calls.
        """
        super().__init__(model_name=model_name, api_base=api_base, timeout=timeout)
        # Ensure the api_base doesn't have trailing slash for clean endpoint construction
        self.api_base = self.api_base.rstrip("/")
        logger.info("Ollama LLM Client initialized (Model: '%s', Base: '%s', Timeout: %.1fs)", self.model_name, self.api_base, self.timeout)

    async def generate(self, prompt: str, system_prompt: Optional[str] = None, **kwargs: Any) -> str:
        """
        Generates a full text response from the local model.

        Args:
            prompt: User text prompt to send.
            system_prompt: Optional system-level prompt guiding model rules/person.
            **kwargs: Extra arguments for parameters like temperature.

        Returns:
            str: Generated completion response text.
        """
        url = f"{self.api_base}/api/generate"
        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "stream": False,
            "options": kwargs
        }
        if system_prompt:
            payload["system"] = system_prompt

        logger.debug("Sending generation request to Ollama: %s", url)

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            try:
                response = await client.post(url, json=payload)
                response.raise_for_status()
                data = response.json()
                result = data.get("response", "").strip()
                logger.info("Ollama response generated successfully (~%d characters).", len(result))
                return result
            except httpx.HTTPStatusError as e:
                logger.error("Ollama HTTP error status: %s. Body: %s", e.response.status_code, e.response.text)
                raise RuntimeError(f"Ollama server returned HTTP error status {e.response.status_code}") from e
            except httpx.RequestError as e:
                logger.error("Failed to connect to local Ollama server at %s: %s", self.api_base, e)
                raise ConnectionError(f"Could not connect to local Ollama server. Ensure Ollama is running offline. Error: {e}") from e

    async def generate_stream(self, prompt: str, system_prompt: Optional[str] = None, **kwargs: Any) -> AsyncIterator[str]:
        """
        Generates a streaming text response from the local model, yielding chunks as they arrive.

        Args:
            prompt: User text prompt to send.
            system_prompt: Optional system-level prompt guiding model rules/person.
            **kwargs: Extra arguments for parameters like temperature.

        Yields:
            str: Next word/token chunk generated by the model.
        """
        url = f"{self.api_base}/api/generate"
        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "stream": True,
            "options": kwargs
        }
        if system_prompt:
            payload["system"] = system_prompt

        logger.debug("Opening generation stream to Ollama: %s", url)

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            try:
                async with client.stream("POST", url, json=payload) as stream:
                    stream.raise_for_status()
                    async for line in stream.aiter_lines():
                        if not line.strip():
                            continue
                        try:
                            data = json.loads(line)
                            chunk = data.get("response", "")
                            if chunk:
                                yield chunk
                            if data.get("done", False):
                                break
                        except json.JSONDecodeError:
                            logger.warning("Failed to decode JSON chunk from Ollama stream: %s", line)
            except httpx.HTTPStatusError as e:
                logger.error("Ollama streaming HTTP error: %s", e)
                raise RuntimeError(f"Ollama streaming server returned HTTP error status {e.response.status_code}") from e
            except httpx.RequestError as e:
                logger.error("Ollama streaming connection error at %s: %s", self.api_base, e)
                raise ConnectionError(f"Could not connect to local Ollama stream. Ensure Ollama is running. Error: {e}") from e
